import { ArrowLeft } from "lucide-react"
import Link from "next/link"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground p-8 md:p-24 font-sans transition-colors duration-500">
      <div className="max-w-3xl mx-auto">
        <Link href="/login" className="inline-flex items-center gap-2 text-cyan-500 hover:text-cyan-400 mb-12 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Login
        </Link>
        
        <h1 className="text-4xl font-bold text-foreground mb-8 tracking-tight">Terms of Service</h1>
        <p className="text-muted-foreground mb-12">Last Updated: May 1, 2026</p>

        <div className="space-y-8 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">1. Acceptance of Terms</h2>
            <p>By accessing and using Deep Research AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">2. AI Research Disclaimer</h2>
            <p>Deep Research AI provides information generated by artificial intelligence. While we strive for accuracy, we cannot guarantee the completeness or reliability of the generated reports. Users should cross-verify critical information.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">3. User Conduct</h2>
            <p>You agree not to use the service for any unlawful purposes or to generate harmful, biased, or infringing content. We reserve the right to suspend accounts that violate these guidelines.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">4. Intellectual Property</h2>
            <p>The reports generated for you are your property. However, the underlying technology, dashboard design, and software remain the intellectual property of Deep Research AI.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-4">5. Limitation of Liability</h2>
            <p>Deep Research AI shall not be liable for any indirect, incidental, or consequential damages resulting from the use or inability to use our research engine.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
